import type { CustomTypes } from "../types"
import type { QueryResult, SqlQuery } from "../types"
import type { CompleteConfig } from "./generate-config"

import { SQL } from "bun"

import { enumDataForSchema, enumTypesForEnumData } from "../shared/generate-enums"
import { header } from "../shared/generate-header"
import {
  relationsInSchema,
  definitionForRelationInSchema,
  crossTableTypesForTables,
  crossSchemaTypesForAllTables,
  crossSchemaTypesForSchemas,
  type Relation
} from "../shared/generate-tables"

const declareModule = (module: string, declarations: string) => `
declare module '${module}' {
  ${declarations.replace(/^(?=[ \t]*\S)/gm, "  ")}
}
`

const customTypeHeader = `/*
** Please edit this file as needed **
It's been generated by Postgres as a custom type definition placeholder, and won't be overwritten
*/
`

function sourceFilesForCustomTypes(customTypes: CustomTypes) {
  return Object.fromEntries(
    Object.entries(customTypes).map(([name, baseType]) => [
      name,
      customTypeHeader +
        declareModule(
          "@brand-map/postgres/custom",
          `${baseType === "db.JsonValue" ? `import type * as db from '@brand-map/postgres/bun';\n` : ``}export type ${name} = ${baseType};  // replace with your custom type or interface as desired`
        )
    ])
  )
}

function indentAll(level: number, s: string) {
  if (level === 0) {
    return s
  }
  return s.replace(/^/gm, " ".repeat(level))
}

interface BunSqlClient {
  unsafe<T = any[]>(query: string, values?: any[]): Promise<T>
  close(options?: { timeout?: number }): Promise<void>
}

type BunModule = { SQL?: new (options?: unknown) => BunSqlClient }

type GenerateTsOutputDeps = {
  loadBunModule: () => Promise<BunModule>
}

const defaultGenerateTsOutputDeps: GenerateTsOutputDeps = {
  loadBunModule: async () => (await import("bun")) as BunModule
}

function normaliseBunSqlOptions(options: CompleteConfig["options"]) {
  if (typeof options === "object" && options !== null && "connectionString" in options && typeof (options as { connectionString?: unknown }).connectionString === "string") {
    return (options as { connectionString: string }).connectionString
  }

  return options
}

async function createBunSqlClient(options: CompleteConfig["options"], deps: GenerateTsOutputDeps): Promise<BunSqlClient> {
  let bunModule: BunModule
  try {
    bunModule = await deps.loadBunModule()
  } catch (err) {
    throw new Error(`This runtime cannot import module "bun"`, { cause: err })
  }

  if (typeof bunModule.SQL !== "function") {
    throw new Error(`Bun.SQL is unavailable`)
  }

  return new bunModule.SQL(normaliseBunSqlOptions(options))
}

function formatBunSqlError(err: SQL.SQLError) {
  if (err instanceof SQL.PostgresError) {
    const sqlState = typeof err.errno === "string" && err.errno.length === 5 ? ` (SQLSTATE ${err.errno})` : ""
    const detail = err.detail ? ` Detail: ${err.detail}` : ""
    const hint = err.hint ? ` Hint: ${err.hint}` : ""
    return `${err.code}${sqlState}: ${err.message}${detail}${hint}`
  }

  return `${(err as { code?: string }).code ?? err.name}: ${err.message}`
}

export const tsForConfig = async (config: CompleteConfig, debug: (s: string) => void, deps: Partial<GenerateTsOutputDeps> = {}) => {
  let querySeq = 0
  const resolvedDeps = { ...defaultGenerateTsOutputDeps, ...deps }
  const { schemas, options } = config
  const bunSql = await createBunSqlClient(options, resolvedDeps)
  const customTypes: CustomTypes = {}
  const schemaNames = Object.keys(schemas)
  let queryChain = Promise.resolve()

  const queryFn = async (query: SqlQuery, seq = querySeq++): Promise<QueryResult<any>> =>
    new Promise<QueryResult<any>>((resolve, reject) => {
      queryChain = queryChain.finally(async () => {
        try {
          debug(`>>> query ${seq} >>>\n${query.text.replace(/^\s+|\s+$/gm, "")}\n+ ${JSON.stringify(query.values)}\n`)
          const rows = await bunSql.unsafe(query.text, query.values)
          if (!Array.isArray(rows)) {
            throw new Error(`Bun SQL query did not return a row array`)
          }
          const result = { rows }
          debug(`<<< result ${seq} <<<\n${JSON.stringify(result, null, 2)}\n`)
          resolve(result)
        } catch (e: unknown) {
          const err = e instanceof SQL.SQLError ? new Error(formatBunSqlError(e), { cause: e }) : e instanceof Error ? e : new Error(String(e))
          const cleanedQuery = query.text.replace(/^\s+|\s+$/gm, "")
          reject(new Error(`Schema generation query ${seq} failed: ${err.message}\nSQL:\n${cleanedQuery}\nvalues: ${JSON.stringify(query.values)}`, { cause: err }))
        }
      })
    })

  try {
    const schemaData = await Promise.all(
      schemaNames.map(async schema => {
        const rules = schemas[schema]
        const tables =
          rules?.exclude === "*"
            ? []
            : // exclude takes precedence
              (await relationsInSchema(schema, queryFn))
                .filter(rel => rules?.include === "*" || rules?.include?.indexOf(rel.name)! >= 0)
                .filter(rel => rules?.exclude.indexOf(rel.name)! < 0)
        const enums = await enumDataForSchema(schema, queryFn)
        const tableDefs = await Promise.all(tables.map(async table => definitionForRelationInSchema(table, schema, enums, customTypes, config, queryFn)))
        const schemaIsUnprefixed = schema === config.unprefixedSchema
        const none = "/* (none) */"
        const schemaDef =
          `/* === schema: ${schema} === */\n` +
          (schemaIsUnprefixed ? "" : `\nexport namespace ${schema} {\n`) +
          indentAll(
            schemaIsUnprefixed ? 0 : 2,
            `\n/* --- enums --- */\n` +
              (enumTypesForEnumData(enums) || none) +
              `\n\n/* --- tables --- */\n` +
              (tableDefs.join("\n") || none) +
              `\n\n/* --- aggregate types --- */\n` +
              (schemaIsUnprefixed ? `\nexport namespace ${schema} {${indentAll(2, crossTableTypesForTables(tables) || none)}\n}\n` : crossTableTypesForTables(tables) || none)
          ) +
          "\n" +
          (schemaIsUnprefixed ? "" : `}\n`)

        return { schemaDef, tables }
      })
    )

    const schemaDefs = schemaData.map(r => r.schemaDef)
    const schemaTables = schemaData.map(r => r.tables)
    const allTables = ([] as Relation[]).concat(...schemaTables)
    const hasCustomTypes = Object.keys(customTypes).length > 0

    const content = [
      `import type * as db from '@brand-map/postgres/bun';`,
      hasCustomTypes ? `import type * as c from '@brand-map/postgres/custom';` : ``,
      schemaDefs.join("\n\n"),
      `/* === global aggregate types === */`,
      crossSchemaTypesForSchemas(schemaNames),
      `/* === lookups === */`,
      crossSchemaTypesForAllTables(allTables, config.unprefixedSchema)
    ].join("\n\n")

    const ts = `
  ${header()}
  
  ${declareModule("@brand-map/postgres/schema", content)}
  `

    const customTypeSourceFiles = sourceFilesForCustomTypes(customTypes)

    return { ts, customTypeSourceFiles }
  } finally {
    await bunSql.close()
  }
}
